#!/usr/bin/env python3
"""Key management and image signing for the secure A/B bootloader.

Image layout (keep in sync with common/image.h):

    0x000  header (128 bytes) + 0xFF padding up to 0x200
    0x200  payload (raw application binary, padded to a multiple of 4)

    header = <magic u32, hdr_version u16, hdr_size u16, load_addr u32,
              img_size u32, version u32, security_counter u32, flags u32,
              reserved u32, payload_sha256[32], signature[64]>

    signature = ECDSA-P256(SHA-256(header[0:64])) encoded as raw r || s.
"""
import argparse
import hashlib
import os
import struct
import sys

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import (
    Prehashed, decode_dss_signature, encode_dss_signature)

MAGIC = 0x31494253          # "SBI1"
HDR_VERSION = 1
HDR_SIZE = 0x200
SIGNED_LEN = 64
SLOT_SIZE = 0x60000
SLOTS = {"A": 0x08020000, "B": 0x08120000}
HDR_FMT = "<IHHIIIIII32s"   # everything before the signature


def load_private(path):
    with open(path, "rb") as f:
        key = serialization.load_pem_private_key(f.read(), password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey) or key.curve.name != "secp256r1":
        sys.exit(f"{path}: not a P-256 private key")
    return key


def load_public(path):
    with open(path, "rb") as f:
        data = f.read()
    if b"PRIVATE" in data:
        return serialization.load_pem_private_key(data, password=None).public_key()
    return serialization.load_pem_public_key(data)


def raw_pubkey(pub):
    nums = pub.public_numbers()
    return nums.x.to_bytes(32, "big") + nums.y.to_bytes(32, "big")


def parse_version(s):
    parts = [int(p) for p in s.split(".")]
    if len(parts) != 3 or not (0 <= parts[0] < 256 and 0 <= parts[1] < 256 and 0 <= parts[2] < 65536):
        raise argparse.ArgumentTypeError("version must be MAJOR.MINOR.PATCH (255.255.65535 max)")
    return (parts[0] << 24) | (parts[1] << 16) | parts[2]


def fmt_version(v):
    return f"{v >> 24}.{(v >> 16) & 0xFF}.{v & 0xFFFF}"


def cmd_keygen(args):
    if os.path.exists(args.out):
        sys.exit(f"{args.out} already exists - refusing to overwrite a signing key")
    key = ec.generate_private_key(ec.SECP256R1())
    pem = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                            serialization.NoEncryption())
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    fd = os.open(args.out, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(pem)
    pub = key.public_key().public_bytes(serialization.Encoding.PEM,
                                        serialization.PublicFormat.SubjectPublicKeyInfo)
    pub_path = os.path.splitext(args.out)[0] + ".pub.pem"
    with open(pub_path, "wb") as f:
        f.write(pub)
    print(f"generated P-256 signing key {args.out} (public: {pub_path})")


def cmd_pubkey_c(args):
    raw = raw_pubkey(load_public(args.key))
    lines = ",\n".join("    " + ", ".join(f"0x{b:02x}" for b in raw[i:i + 8])
                       for i in range(0, 64, 8))
    src = ("/* Generated by tools/imgtool.py from %s - do not edit. */\n"
           "#include <stdint.h>\n\n"
           "/* ECDSA P-256 public key, uncompressed X || Y (big-endian). */\n"
           "const uint8_t boot_public_key[64] = {\n%s\n};\n") % (os.path.basename(args.key), lines)
    with open(args.out, "w") as f:
        f.write(src)


def cmd_sign(args):
    key = load_private(args.key)
    with open(args.input, "rb") as f:
        payload = f.read()
    payload += b"\xff" * (-len(payload) % 4)
    if len(payload) > SLOT_SIZE - HDR_SIZE:
        sys.exit(f"payload too large ({len(payload)} bytes)")

    # Sanity-check that the binary really is linked for this slot.
    sp, reset = struct.unpack_from("<II", payload, 0)
    lo = args.load_addr + HDR_SIZE
    if not (lo <= (reset & ~1) < lo + len(payload)):
        sys.exit(f"reset vector 0x{reset:08x} is outside slot at 0x{args.load_addr:08x} "
                 "- binary linked for the wrong slot?")

    head = struct.pack(HDR_FMT, MAGIC, HDR_VERSION, HDR_SIZE, args.load_addr, len(payload),
                       args.version, args.security_counter, 0, 0,
                       hashlib.sha256(payload).digest())
    assert len(head) == SIGNED_LEN
    digest = hashlib.sha256(head).digest()
    der = key.sign(digest, ec.ECDSA(Prehashed(hashes.SHA256())))
    r, s = decode_dss_signature(der)
    header = head + r.to_bytes(32, "big") + s.to_bytes(32, "big")
    header += b"\xff" * (HDR_SIZE - len(header))

    with open(args.output, "wb") as f:
        f.write(header + payload)
    print(f"signed {args.output}: v{fmt_version(args.version)} counter {args.security_counter} "
          f"slot @0x{args.load_addr:08x} payload {len(payload)} bytes")


def parse_image(data):
    if len(data) < HDR_SIZE:
        raise ValueError("file too small")
    fields = struct.unpack_from(HDR_FMT, data, 0)
    (magic, hver, hsize, load, size, ver, ctr, flags, _res, phash) = fields
    sig = data[SIGNED_LEN:SIGNED_LEN + 64]
    return dict(magic=magic, hdr_version=hver, hdr_size=hsize, load_addr=load, img_size=size,
                version=ver, security_counter=ctr, flags=flags, payload_sha256=phash,
                signature=sig)


def verify_image(data, pub):
    h = parse_image(data)
    if h["magic"] != MAGIC:
        return h, "bad magic"
    payload = data[HDR_SIZE:HDR_SIZE + h["img_size"]]
    if len(payload) != h["img_size"] or hashlib.sha256(payload).digest() != h["payload_sha256"]:
        return h, "payload hash mismatch"
    if pub is None:
        return h, "hash OK (signature not checked, no key given)"
    r = int.from_bytes(h["signature"][:32], "big")
    s = int.from_bytes(h["signature"][32:], "big")
    try:
        pub.verify(encode_dss_signature(r, s), hashlib.sha256(data[:SIGNED_LEN]).digest(),
                   ec.ECDSA(Prehashed(hashes.SHA256())))
    except InvalidSignature:
        return h, "SIGNATURE INVALID"
    return h, "signature OK"


def cmd_info(args):
    with open(args.input, "rb") as f:
        data = f.read()
    pub = load_public(args.key) if args.key else None
    h, status = verify_image(data, pub)
    slot = next((n for n, a in SLOTS.items() if a == h["load_addr"]), "?")
    print(f"{args.input}:")
    print(f"  version          {fmt_version(h['version'])}")
    print(f"  security counter {h['security_counter']}")
    print(f"  load address     0x{h['load_addr']:08x} (slot {slot})")
    print(f"  payload          {h['img_size']} bytes, sha256 {h['payload_sha256'].hex()}")
    print(f"  status           {status}")
    return 0 if "OK" in status else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("keygen", help="generate a new P-256 signing key")
    p.add_argument("out")
    p.set_defaults(fn=cmd_keygen)

    p = sub.add_parser("pubkey-c", help="emit the public key as C source")
    p.add_argument("key")
    p.add_argument("out")
    p.set_defaults(fn=cmd_pubkey_c)

    p = sub.add_parser("sign", help="wrap a raw binary in a signed header")
    p.add_argument("--key", required=True)
    p.add_argument("--load-addr", required=True, type=lambda s: int(s, 0))
    p.add_argument("--version", required=True, type=parse_version)
    p.add_argument("--security-counter", required=True, type=int)
    p.add_argument("input")
    p.add_argument("output")
    p.set_defaults(fn=cmd_sign)

    p = sub.add_parser("info", help="show and verify a signed image")
    p.add_argument("--key")
    p.add_argument("input")
    p.set_defaults(fn=cmd_info)

    args = ap.parse_args()
    sys.exit(args.fn(args) or 0)


if __name__ == "__main__":
    main()
